# Generated by Django 5.1.7 on 2025-04-08 23:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_produto_quantidade'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avatar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='avatares')),
                ('Usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='App.usuario')),
            ],
        ),
    ]
