# Generated by Django 5.1.7 on 2025-04-18 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_alter_usuario_password_alter_usuario_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='data_modificao',
            new_name='data_modificacao',
        ),
    ]
